In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [7]:
import pandas as pd

data = pd.read_csv("student_performance_dataset.csv")
data

Hours_Studied  Attendance  Assignments_Score  Previous_Grade Final_Result
0               2          60                 50              55         Fail
1               3          65                 55              58         Fail
2               4          70                 60              60         Pass
3               5          75                 65              62         Pass
4               6          80                 70              68         Pass
5               1          50                 40              45         Fail
6               7          85                 75              72         Pass
7               8          90                 80              78         Pass
8               2          55                 48              50         Fail
9               9          95                 88              85         Pass
10              3          60                 52              54         Fail
11              4          68                 58              59         Pass
12              5          72                 63              64         Pass
13              6          78                 69              70         Pass
14              1          45                 35              40         Fail
15              7          82                 73              74         Pass
16              8          88                 85              80         Pass
17              2          58                 47              52         Fail
18              9          92                 90              88         Pass
19              3          63                 53              56         Fail

In [13]:
x=data.iloc[:,:4]
x

Hours_Studied  Attendance  Assignments_Score  Previous_Grade
0               2          60                 50              55
1               3          65                 55              58
2               4          70                 60              60
3               5          75                 65              62
4               6          80                 70              68
5               1          50                 40              45
6               7          85                 75              72
7               8          90                 80              78
8               2          55                 48              50
9               9          95                 88              85
10              3          60                 52              54
11              4          68                 58              59
12              5          72                 63              64
13              6          78                 69              70
14              1          45                 35              40
15              7          82                 73              74
16              8          88                 85              80
17              2          58                 47              52
18              9          92                 90              88
19              3          63                 53              56

In [14]:
y=data.iloc[:,4]
y

0     Fail
1     Fail
2     Pass
3     Pass
4     Pass
5     Fail
6     Pass
7     Pass
8     Fail
9     Pass
10    Fail
11    Pass
12    Pass
13    Pass
14    Fail
15    Pass
16    Pass
17    Fail
18    Pass
19    Fail
Name: Final_Result, dtype: object

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.3, random_state=42)

In [17]:
lr = LogisticRegression(max_iter=200)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=200)

In [19]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [20]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [21]:
svm=SVC()
svm.fit(x_train,y_train)

SVC()

In [22]:
y_pred=lr.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy 1.0
[[5 0]
 [0 1]]
              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         5
        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6



In [23]:
y_pred=dt.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy 0.8333333333333334
[[4 1]
 [0 1]]
              precision    recall  f1-score   support

        Fail       1.00      0.80      0.89         5
        Pass       0.50      1.00      0.67         1

    accuracy                           0.83         6
   macro avg       0.75      0.90      0.78         6
weighted avg       0.92      0.83      0.85         6



In [24]:
y_pred=svm.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy 0.3333333333333333
[[1 4]
 [0 1]]
              precision    recall  f1-score   support

        Fail       1.00      0.20      0.33         5
        Pass       0.20      1.00      0.33         1

    accuracy                           0.33         6
   macro avg       0.60      0.60      0.33         6
weighted avg       0.87      0.33      0.33         6



In [25]:
y_pred=rf.predict(x_test)
print("Accuracy",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy 1.0
[[5 0]
 [0 1]]
              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         5
        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6



In [27]:
models={
    "LogisticRegression":lr,
    "DecisionTreeClassifier":dt,
    "RandomForestClassifier":rf,
    "SVC":svm
}
for name,model in models.items():
  y_pred=model.predict(x_test)
  print(name,"Accuracy:",accuracy_score(y_test,y_pred))


LogisticRegression Accuracy: 1.0
DecisionTreeClassifier Accuracy: 0.8333333333333334
RandomForestClassifier Accuracy: 1.0
SVC Accuracy: 0.3333333333333333
